name: saas_flutter_module
description: 目前应用于saas商家端
version: 1.0.0

homepage: https://weilu.blog.csdn.net/
publish_to: 'none'
environment:
  sdk: ">=3.0.0-0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0
  # Localization https://github.com/dart-lang/intl
  intl: ^0.18.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.3.2
  # 网络库 https://github.com/cfug/dio
  dio: ^5.3.3
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.1.0
  sp_util: 2.0.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars_flutter3: ^3.0.0 # flustars很久不维护，可以使用这个替代
  # Flutter 轮播图 https://github.com/mdddj/flutter_swiper_null_safety
  flutter_swiper_null_safety_flutter3: ^4.0.0   # flutter_swiper很久不维护，可以使用这个替代
  # 启动URL的插件（支持Web） https://github.com/flutter/packages/tree/main/packages/url_launcher
  url_launcher: 6.1.8
  # 图片选择插件 https://github.com/flutter/packages/tree/main/packages/image_picker
  image_picker: 1.0.4
  # WebView插件 https://github.com/flutter/packages/tree/main/packages/webview_flutter
  webview_flutter: 4.2.4
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.2.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.5
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.3.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^7.0.0
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 9.0.2
  #  城市选择器 https://github.com/longer96/flutter_pickers#%E6%A0%B7%E5%BC%8F
  flutter_pickers: ^2.1.8
  # amap
  amap_flutter_map: ^3.0.0
  # 状态管理
  flutter_riverpod: ^2.4.9
  # 原生数据共享
  pigeon: ^15.0.2

# https://github.com/simplezhli/flutter_deer/issues/187
dependency_overrides:
  scrollable_positioned_list: ^0.3.2


dev_dependencies:
  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # 黄金测试
  #  flutter_goldens:
  #    sdk: flutter
  # 单元测试
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https:/w.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  module:
    androidX: true
    androidPackage: com.immotor.flutter.saas_flutter_module
    iosBundleIdentifier: com.immotor.flutter.saasFlutterModule
