// Autogenerated from Pigeon (v15.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTNetHeaderBean;
@class FLTBatteryMapBean;

@interface FLTNetHeaderBean : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAuthorization:(NSString *)authorization
    userAgent:(NSString *)userAgent
    cityCode:(NSString *)cityCode
    acceptLanguage:(NSString *)acceptLanguage;
@property(nonatomic, copy) NSString * authorization;
@property(nonatomic, copy) NSString * userAgent;
@property(nonatomic, copy) NSString * cityCode;
@property(nonatomic, copy) NSString * acceptLanguage;
@end

@interface FLTBatteryMapBean : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAddress:(NSString *)address
    latitude:(double )latitude
    longitude:(double )longitude
    time:(NSString *)time;
@property(nonatomic, copy) NSString * address;
@property(nonatomic, assign) double  latitude;
@property(nonatomic, assign) double  longitude;
@property(nonatomic, copy) NSString * time;
@end

/// The codec used by FLTFlutterToNative.
NSObject<FlutterMessageCodec> *FLTFlutterToNativeGetCodec(void);

@protocol FLTFlutterToNative
/// @return `nil` only when `error != nil`.
- (nullable FLTNetHeaderBean *)getNetHeaderBeanWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FLTBatteryMapBean *)getBatteryMapBeanWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)navigationWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFLTFlutterToNative(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTFlutterToNative> *_Nullable api);

NS_ASSUME_NONNULL_END
